version: '2'
services:
  torrentmonitor:
    container_name: ${CONTAINER_NAME}
    hostname: torrentmonitor
    image: nawa/torrentmonitor
    restart: ${RESTART_POLICY}
    ports:
      - ${LISTEN_PORT}:${HTTP_PORT}/tcp
    volumes:
      - ${TORRENTS}:/data/htdocs/torrents
      - ${DB}:/data/htdocs/db
    environment:
      - CRON_TIMEOUT=${CRON_TIMEOUT}
      - PHP_TIMEZONE=${PHP_TIMEZONE}
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT}
